{
  "hash": "1065e50368c5efa9e971cec7afe58e72",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 4: The tidyverse\"\n---\n\n<!-- Shared format options live in _metadata.yml, so this deck's YAML carries only the title.\n\n     This week teaches code, so the code has to be visible: every teaching chunk opts out of the\n     default fold with #| code-fold: false, as in week 03.\n\n     Rhythm: every concept is followed by a \"Practice:\" slide the room does on the spot, with the\n     answer behind a . . . beat. The red line is ONE story: read a messy file, make it tidy, then\n     transform, join and summarise, while a single gapminder pipeline grows one verb at a time\n     (the new line is highlighted with code-line-numbers). It ends in a pipeline the room writes.\n\n     Time budget (90 min): cell options and errors 4, packages 10, tidyverse and tidy data 10,\n     read 8, tidy 6, transform 17, join 9, count and summarise 10, pipeline and bonus 14,\n     wrap-up 2.\n     If the room runs slow, cut arrange first, then pivot_wider, then the kable bonus.\n\n     data/week04-lifeexp-wide.csv is gapminder's life expectancy for the nine countries of the\n     hw-03 `europe` table, pivoted wide (one column per year) and written once with:\n       gapminder |> filter(country %in% nine) |> select(country, year, lifeExp) |>\n         pivot_wider(names_from = year, values_from = lifeExp) |> write_csv(...)\n\n     data/eu-members.csv is typed by hand: every EU member state with its accession date, plus\n     the United Kingdom with its exit date (europa.eu, \"EU countries\"). Founders date from the\n     EEC treaty entering into force, 1958-01-01, and Germany means West Germany until 1990.\n     Country names follow gapminder's spelling (Czech Republic, Slovak Republic) so the join is\n     clean. Six members are not in gapminder at all (Luxembourg, Cyprus, the Baltics, Malta).\n\n     Students read both files from their raw GitHub URLs, so both must be pushed before class. -->\n\n\n\n## Week 4 goals {#sec-week04-goals .smaller}\n\nBy the end of today, you will be able to:\n\n1. Install and load packages, and call a function as `package::function()`.\n2. Say what the tidyverse is and what makes data tidy.\n3. Read a file and reshape it into tidy form.\n4. Transform, join and summarise data in one readable pipeline.\n5. Answer a question with a pipeline, and report the answer as a captioned table.\n\n## Today {#sec-today .smaller}\n\n1. **Before we start:** cell options and error messages, in brief\n2. **Packages:** install, load, `package::function()`\n3. **The tidyverse** and tidy data\n4. **Read, tidy, transform:** one dataset, one growing pipeline\n   - `read_csv()`, `pivot_longer()`, the `dplyr` verbs, `left_join()`, `count()`, `summarise()`\n5. **Your pipeline:** from a question to an answer\n\n::: notes\nSame deal as last week: type along.\nPositron open, a fresh `.qmd` or the console.\n:::\n\n## Where today fits {#sec-where-today-fits .smaller}\n\nToday starts **step 2, the data summary**.\nEvery data summary you will write this term is a pipeline like the one we build today.\n\n<!--\nCANONICAL 8-STEP BAYESIAN WORKFLOW. Single source of truth.\nInclude this partial wherever the workflow is shown:\n    {{< include _workflow-8step.qmd >}}          (from within slides/)\n    {{< include slides/_workflow-8step.qmd >}}   (from the site root, e.g. syllabus.qmd)\nDo NOT copy this table into individual decks (E042). Edit it here only.\nThis is the rubric the exam is graded against and the structure the AI feedback follows.\n-->\n\n::: {.small}\n| # | Step | What you produce |\n|--:|------|------------------|\n| 1 | **Estimand** | The quantity you want to learn about, stated precisely as a target before any model is fitted. |\n| 2 | **Data summary** | The data described: measurement, coverage, obvious issues. |\n| 3 | **Formal model** | Likelihood and priors written down, the generative model. |\n| 4 | **Prior predictive check** | Simulate from the priors, confirm they imply plausible data. |\n| 5 | **Fit** | Estimate with `brms`, weakly-informative priors by default. |\n| 6a | **MCMC diagnostics** | R-hat, ESS, divergences, trace plots. Did sampling work? |\n| 6b | **Posterior predictive check** | Does the fitted model reproduce key features of the data? |\n| 7 | **Interpretation** | Answer the estimand on the outcome scale, with uncertainty. |\n| 8 | **Limitations** | What the analysis can and cannot support, threats and next steps. |\n\n: The 8-step Bayesian workflow. Every homework exercises the steps introduced so far, cumulatively, and the exam runs all eight end to end. {#tbl-workflow}\n:::\n\n\n::: notes\nOne minute.\nPoint at step 2 only.\n:::\n\n# Before we start: cell options and errors {#sec-before-we-start}\n\n## Cell options you have met {#sec-cell-options-table .smaller}\n\n::: notes\nTwo minutes, no practice.\nThey used label, echo, eval and error in hw-03.\nPoint at include, message, warning and the two captions as the new ones.\n:::\n\n::: {.small}\n| Option | What it does |\n|---|---|\n| `label: my-name` | Names the cell. Unique, and required. |\n| `echo: false` | Runs the code, hides it, shows the result. |\n| `eval: false` | Shows the code, does not run it. |\n| `include: false` | Runs the code, shows nothing at all. |\n| `error: true` | Shows an error and keeps rendering. |\n| `message: false` | Hides messages, such as package startup text. |\n| `warning: false` | Hides warnings. |\n| `fig-cap: \"...\"` | Captions a figure, with a `fig-` label. |\n| `tbl-cap: \"...\"` | Captions a table, with a `tbl-` label. |\n\n: The cell options this course uses, one `#|` line each at the top of a cell. Set under `execute:` in the YAML header, an option applies to every cell instead. {#tbl-cell-options}\n:::\n\n## Errors: which layer is complaining? {#sec-render-relay .smaller}\n\n::: notes\nTwo minutes, no practice.\nThe one idea: the first word of the message tells you which runner dropped the baton.\n:::\n\n`.qmd` → **R** runs the cells → `.md` → **Quarto and Pandoc** convert → `.tex` → **LaTeX** typesets → `.pdf`\n\n::: {.small}\n| Layer | The message looks like | Where to look |\n|---|---|---|\n| **R** | `Error:` or `Error in f():`, then `Quitting from hw.qmd:6-10 [cell-label]` | The cell named in square brackets, at those lines. |\n| **Quarto** | `ERROR: YAMLException: ... (6:20)` | The YAML header, at line 6, column 20. |\n| **LaTeX** | `compilation failed- error`, then a line number `l.172` | Your prose: a special character such as `%`, `&`, `$` or a stray `\\`. |\n\n: The three layers of a PDF render, how each one reports a failure, and where to go to fix it. {#tbl-error-layers}\n:::\n\n::: {.callout-tip}\n**Only the first error counts.**\nScroll up to the first message, fix that, and render again.\n:::\n\n# Packages {#sec-packages}\n\n## Packages: functions other people wrote {#sec-what-packages .smaller}\n\n::: notes\nCallback to week 3: they wrote `celsius_to_fahrenheit()`.\nA package is that, times a few hundred, with documentation, shared.\n:::\n\nLast week you wrote your own function.\nA **package** is a bundle of functions, their help pages, and sometimes data, that someone wrote and shared.\n\n. . .\n\n- R itself ships with the **base** packages: `mean()`, `round()`, `data.frame()`.\n- **CRAN**, R's package archive, holds more than 20,000 more, checked and free.\n- Nearly every method in this course lives in a package: `dplyr` today, `ggplot2` next week, `brms` later.\n\n## Install once, load every session {#sec-install-load .smaller}\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n**Install** downloads the package to your computer.\nOnce, in the **console**.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ninstall.packages(\"gapminder\")\n```\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n**Load** makes its functions available.\nEvery session, at the top of your `.qmd`.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(gapminder) # demo data\n```\n:::\n\n:::\n\n::::\n\n. . .\n\nLike an app on your phone: you install it once, and you open it every time you use it.\n\n::: {.callout-important}\n**`install.packages()` never goes into a `.qmd`.**\nIt would reinstall on every render, and Quarto refuses to run it anyway.\n:::\n\n## Quarto stops when a package is missing {#sec-missing-package .smaller}\n\nIf a `library()` call names a package that is not installed, the render stops at that cell:\n\n```text\nError in `library()`:\n! there is no package called 'gapminder'\nQuitting from hw-04.qmd:6-10 [setup]\n```\n\n. . .\n\n- That is an **R** error, reported through Quarto.\n- The fix is in the **console**, not in the document: `install.packages(\"gapminder\")`, then render again.\n- It also happens when the name is misspelled: `library(gapmindr)` gives the same message.\n\n::: notes\nThis is the most common first-render failure on a new laptop.\nEverybody who installed a package in a different R version meets it once.\n:::\n\n## `package::function()` {#sec-double-colon .smaller}\n\n`::` names the package a function comes from.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ngapminder::gapminder |> nrow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1704\n```\n\n\n:::\n:::\n\n\n. . .\n\nThree reasons when it can be useful:\n\n- **Clarity:** the reader sees where a function lives.\n- **No `library()` needed** for a one-off call, such as `readxl::read_excel()`.\n- **Name clashes:** two packages can both have a `filter()`.\n  `library(tidyverse)` tells you which one wins: `✖ dplyr::filter() masks stats::filter()`.\n\n`?dplyr::filter` opens the help page of that exact function.\nMost packages also have good online documentation, such as [dplyr.tidyverse.org](https://dplyr.tidyverse.org).\n\n::: {.callout-tip}\n**Rule of thumb: more than three calls, load the package.**\nOnce you use a package's functions more than three times, add a `library()` line to your setup cell instead of repeating `package::` every time.\n:::\n\n## Practice: install and load {#sec-practice-packages .smaller}\n\n::: notes\nCirculate.\nAnyone whose `library(tidyverse)` fails installs it now.\n:::\n\n**Do this now.**\n\n1. In the **console**, install `gapminder`.\n2. At the top of your `.qmd`, load `tidyverse` and `gapminder` in a setup cell.\n   Run the cell and read the startup message.\n   Which packages were attached, and what is masked?\n3. Type `gapminder` and run it.\n   How many rows and columns?\n4. Run `?gapminder`.\n   What does `gdpPercap` measure?\n\n## Practice: install and load, solution {#sec-practice-packages-solution .smaller}\n\n:::: {.columns}\n\n::: {.column width=\"55%\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(tidyverse) # wrangling\nlibrary(gapminder) # demo data\n\ngapminder\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,704 × 6\n  country     continent  year lifeExp      pop gdpPercap\n  <fct>       <fct>     <int>   <dbl>    <int>     <dbl>\n1 Afghanistan Asia       1952    28.8  8425333      779.\n2 Afghanistan Asia       1957    30.3  9240934      821.\n3 Afghanistan Asia       1962    32.0 10267083      853.\n4 Afghanistan Asia       1967    34.0 11537966      836.\n5 Afghanistan Asia       1972    36.1 13079460      740.\n# ℹ 1,699 more rows\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"45%\"}\n1. `install.packages(\"gapminder\")`, in the console only.\n2. The nine core packages, from `dplyr` to `tidyr`.\n   `dplyr::filter()` and `dplyr::lag()` mask their namesakes from `stats`.\n3. **1704 rows** and **6 columns**.\n4. GDP per capita, in US dollars and adjusted for inflation.\n:::\n\n::::\n\n# The tidyverse {#sec-tidyverse}\n\n## One grammar across many packages {#sec-tidyverse-philosophy .smaller}\n\nThe **tidyverse** is a family of packages built on one shared philosophy:\n\n. . .\n\n- **Tidy data in, tidy data out:** every function takes a table and returns a table.\n- **Data first:** the table is always the first argument, so every step chains with `|>`.\n- **Functions are verbs:** `filter()`, `select()` and `summarise()` read like what they do.\n- **Written for humans:** consistent names and arguments, so learning one package teaches you the next.\n\n. . .\n\n`library(tidyverse)` loads the core packages in one line.\n\n::: notes\nTwo minutes.\nThe payoff of the design: tomorrow's package already feels familiar.\n:::\n\n## What is tidy data? {#sec-tidy-data .smaller}\n\n> Tidy datasets are all alike, but every messy dataset is messy in its own way.\n>\n> Hadley Wickham\n\n. . .\n\nA dataset is **tidy** when:\n\n1. Each **variable** has its own **column**.\n2. Each **observation** has its own **row**.\n3. Each **value** has its own **cell**.\n\n. . .\n\nThis is the data frame from week 3, with one rule added: **decide what a row is**.\nIn gapminder, a row is one country in one year.\n\n## Practice: is this tidy? {#sec-practice-tidy .smaller}\n\n**Do this now.**\nTidy or not?\nIf not, which rule does it break?\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n::: {.small}\n| country | year | lifeExp |\n|---|---|---|\n| Germany | 1952 | 67.5 |\n| Germany | 2007 | 79.4 |\n\n: Layout A. {#tbl-layout-a}\n\n| country | 1952 | 2007 |\n|---|---|---|\n| Germany | 67.5 | 79.4 |\n| France | 67.4 | 80.7 |\n\n: Layout B. {#tbl-layout-b}\n:::\n:::\n\n::: {.column width=\"50%\"}\n::: {.small}\n| country | year | measure | value |\n|---|---|---|---|\n| Germany | 2007 | lifeExp | 79.4 |\n| Germany | 2007 | pop | 82400996 |\n\n: Layout C. {#tbl-layout-c}\n\n| country | year | life_range |\n|---|---|---|\n| Germany | 1952-2007 | 67.5-79.4 |\n\n: Layout D. {#tbl-layout-d}\n:::\n:::\n\n::::\n\n. . .\n\nA is tidy.\nB hides the variable `year` in its column names.\nC stores two variables in rows.\nD puts two values in each cell.\n\n::: notes\nHands up for each one before revealing.\nB is the one we meet on the next slides: it is our file.\n:::\n\n## The core packages, along the data cycle {#sec-core-packages .smaller}\n\n**Read** → **Tidy** → **Transform** → Visualise → Model → Communicate\n\n::: {.small}\n| Stage | Package | For | Key functions |\n|---|---|---|---|\n| Read | `readr` | Text files such as CSV | `read_csv()`, `write_csv()` |\n| Tidy | `tidyr` | Reshaping | `pivot_longer()`, `pivot_wider()` |\n| Transform | `dplyr` | The verbs of data manipulation | `filter()`, `mutate()`, `summarise()` |\n| Transform | `stringr`, `forcats`, `lubridate` | Text, factors, dates | `str_detect()`, `fct_reorder()`, `ymd()` |\n| Visualise | `ggplot2` | Plots, next week | `ggplot()` |\n| Underneath | `tibble`, `purrr` | Data frames, repetition | `tibble()`, `map()` |\n\n: The core tidyverse packages, ordered along the data cycle. Today covers the first three stages. {#tbl-core-packages}\n:::\n\n::: {.small}\n::: {.callout-note}\n**In a real project the cycle loops.**\nA plot reveals an odd value, and you go back to tidy or transform again, sometimes many times over.\n:::\n:::\n\n::: notes\nDo not read the table.\nPoint at the three stages we cover, then move on.\n:::\n\n# Read {#sec-read}\n\n## Every format has a reader {#sec-import-formats .smaller}\n\n::: {.small}\n| Format | Extension | Function | Loaded by `library(tidyverse)`? |\n|---|---|---|---|\n| Comma-separated | `.csv` | `readr::read_csv()` | yes |\n| Semicolon-separated | `.csv` | `readr::read_csv2()` | yes |\n| Tab-separated | `.tsv` | `readr::read_tsv()` | yes |\n| R's own format | `.rds` | `readr::read_rds()` | yes |\n| Excel | `.xlsx`, `.xls` | `readxl::read_excel()` | installed, not loaded |\n| Stata | `.dta` | `haven::read_dta()` | installed, not loaded |\n| SPSS | `.sav` | `haven::read_sav()` | installed, not loaded |\n| JSON | `.json` | `jsonlite::fromJSON()` | installed, not loaded |\n| Parquet | `.parquet` | `arrow::read_parquet()` | install it yourself |\n\n: Common data formats and the function that reads each one. Installing the tidyverse also installs `readxl`, `haven` and `jsonlite`, but `library(tidyverse)` loads only `readr`. {#tbl-import-formats}\n:::\n\n::: notes\nPoint out the German Excel row: a CSV that comes out as one column is usually a semicolon file.\nThe next homework reads an `.xlsx` with `readxl::read_excel()`.\n:::\n\n## Reading a file {#sec-read-csv .smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\npath <- here(\"website\", \"slides\", \"data\", \"week04-lifeexp-wide.csv\")\nlifeexp_wide <- read_csv(path)\nglimpse(lifeexp_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 9\nColumns: 13\n$ country <chr> \"France\", \"Germany\", \"Italy\", \"Norway\", \"Poland\", \"S…\n$ `1952`  <dbl> 67.410, 67.500, 65.940, 72.670, 61.310, 64.940, 71.8…\n$ `1957`  <dbl> 68.930, 69.100, 67.810, 73.440, 65.770, 66.660, 72.4…\n$ `1962`  <dbl> 70.510, 70.300, 69.240, 73.470, 67.640, 69.690, 73.3…\n$ `1967`  <dbl> 71.550, 70.800, 71.060, 74.080, 69.610, 71.440, 74.1…\n$ `1972`  <dbl> 72.380, 71.000, 72.190, 74.340, 70.850, 73.060, 74.7…\n$ `1977`  <dbl> 73.830, 72.500, 73.480, 75.370, 70.670, 74.390, 75.4…\n$ `1982`  <dbl> 74.890, 73.800, 74.980, 75.970, 71.320, 76.300, 76.4…\n$ `1987`  <dbl> 76.340, 74.847, 76.420, 75.890, 70.980, 76.900, 77.1…\n$ `1992`  <dbl> 77.460, 76.070, 77.440, 77.320, 70.990, 77.570, 78.1…\n$ `1997`  <dbl> 78.640, 77.340, 78.820, 78.320, 72.750, 78.770, 79.3…\n$ `2002`  <dbl> 79.590, 78.670, 80.240, 79.050, 74.670, 79.780, 80.0…\n$ `2007`  <dbl> 80.657, 79.406, 80.546, 80.196, 75.563, 80.941, 80.8…\n```\n\n\n:::\n:::\n\n\n. . .\n\n::: {.small}\n- **Assign the result.** `read_csv()` alone prints the data and forgets it.\n- `here()` builds the path from your project folder, so it works on any computer.\n  In your homework repository that is `here(\"data\", \"parlgov.xlsx\")`.\n- `glimpse()` shows every column with its type: the first thing to run on new data.\n:::\n\n## Practice: read it yourself {#sec-practice-read .smaller}\n\n**Do this now.**\n`read_csv()` also reads straight from the web.\nBoth files live in the course repository on GitHub.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nbase <- \"https://raw.githubusercontent.com/qmir-2026-fall/qmir-2026-fall.github.io/main/website/slides/data/\"\nlifeexp_wide <- read_csv(paste0(base, \"week04-lifeexp-wide.csv\")) # paste0(): paste() without spaces\neu_members <- read_csv(paste0(base, \"eu-members.csv\"))\n```\n:::\n\n\n1. Read both files and `glimpse()` each.\n2. Which rule of tidy data does `lifeexp_wide` break?\n   A tidy version has one row per country and year: how many rows will it have?\n3. What is a row of `eu_members`, and which type did `accession_date` get?\n\n. . .\n\n::: {.small}\n1. `glimpse(lifeexp_wide)` and `glimpse(eu_members)`.\n2. It is Layout B: `year` hides in the column names.\n   Nine countries times twelve years makes **108 rows**.\n3. One EU member state, 28 rows including the United Kingdom, which left in 2020.\n   `accession_date` is a **`<date>`**: `read_csv()` recognises `2004-05-01` as a date by itself.\n:::\n\n# Tidy {#sec-tidy}\n\n## `pivot_longer()`: wide to tidy {#sec-pivot-longer .smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlifeexp <- lifeexp_wide |>\n  pivot_longer(\n    cols = -country, # every column except country\n    names_to = \"year\", # the column names become this variable\n    values_to = \"lifeExp\" # the cell values become this one\n  )\nlifeexp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 108 × 3\n  country year  lifeExp\n  <chr>   <chr>   <dbl>\n1 France  1952     67.4\n2 France  1957     68.9\n3 France  1962     70.5\n4 France  1967     71.6\n5 France  1972     72.4\n# ℹ 103 more rows\n```\n\n\n:::\n:::\n\n\n::: notes\nRead the call aloud as a sentence: take every column except country, put the names into year and the values into lifeExp.\n:::\n\n## `pivot_wider()`: the way back {#sec-pivot-wider .smaller}\n\nWide is not wrong.\nIt is how a **table for a reader** usually looks, and `pivot_wider()` gets you there:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlifeexp |>\n  pivot_wider(names_from = year, values_from = lifeExp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 13\n  country `1952` `1957` `1962` `1967` `1972` `1977` `1982` `1987`\n  <chr>    <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>\n1 France    67.4   68.9   70.5   71.6   72.4   73.8   74.9   76.3\n2 Germany   67.5   69.1   70.3   70.8   71     72.5   73.8   74.8\n3 Italy     65.9   67.8   69.2   71.1   72.2   73.5   75.0   76.4\n4 Norway    72.7   73.4   73.5   74.1   74.3   75.4   76.0   75.9\n5 Poland    61.3   65.8   67.6   69.6   70.8   70.7   71.3   71.0\n# ℹ 4 more rows\n# ℹ 4 more variables: `1992` <dbl>, `1997` <dbl>, `2002` <dbl>,\n#   `2007` <dbl>\n```\n\n\n:::\n:::\n\n\n. . .\n\n::: {.callout-tip}\n**Tidy for the computer, wide for the reader.**\nKeep your working data tidy, and pivot wider only at the very end, for a table in your report.\n:::\n\n## Practice: pivot it {#sec-practice-pivot .smaller}\n\n::: notes\nThe transition to gapminder is the key sentence here.\nOur file was a slice of gapminder all along.\n:::\n\n**Do this now.**\n\n1. Pivot `lifeexp_wide` into a tidy tibble called `lifeexp`.\n2. Check with `nrow()` that it has 108 rows.\n3. **Stretch:** pivot it back to wide.\n\n## Practice: pivot it, solution {#sec-practice-pivot-solution .smaller}\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlifeexp <- lifeexp_wide |>\n  pivot_longer(\n    cols = -country,\n    names_to = \"year\",\n    values_to = \"lifeExp\"\n  )\nnrow(lifeexp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 108\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# stretch\nlifeexp |>\n  pivot_wider(\n    names_from = year,\n    values_from = lifeExp\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 13\n  country `1952` `1957` `1962` `1967` `1972` `1977` `1982` `1987`\n  <chr>    <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>\n1 France    67.4   68.9   70.5   71.6   72.4   73.8   74.9   76.3\n2 Germany   67.5   69.1   70.3   70.8   71     72.5   73.8   74.8\n3 Italy     65.9   67.8   69.2   71.1   72.2   73.5   75.0   76.4\n4 Norway    72.7   73.4   73.5   74.1   74.3   75.4   76.0   75.9\n5 Poland    61.3   65.8   67.6   69.6   70.8   70.7   71.3   71.0\n# ℹ 4 more rows\n# ℹ 4 more variables: `1992` <dbl>, `1997` <dbl>, `2002` <dbl>,\n#   `2007` <dbl>\n```\n\n\n:::\n:::\n\n:::\n\n::::\n\nFrom here on we use the full `gapminder`: it is this tibble for all 142 countries, with three more variables.\n\n# Transform {#sec-transform}\n\n## The `dplyr` verbs {#sec-dplyr-verbs .smaller}\n\n:::: {.columns}\n\n::: {.column width=\"60%\"}\n::: {.small}\n| Verb | What it does |\n|---|---|\n| `filter()` | Keep rows that meet a condition |\n| `slice()` | Keep rows by position |\n| `select()` | Keep or drop columns |\n| `mutate()` | Create new columns or change old ones |\n| `arrange()` | Sort rows |\n| `left_join()` | Add columns from another table |\n| `count()` | Count rows per value of a column |\n| `group_by()` | Split rows into groups |\n| `summarise()` | Summary statistics, such as a mean, per group |\n\n: The core `dplyr` verbs covered today. Each takes a table and returns a table, so they chain into one pipeline. {#tbl-dplyr-verbs}\n:::\n:::\n\n::: {.column width=\"40%\"}\n::: {.small}\nEvery verb:\n\n- takes a **table first**, so it pipes\n- names columns **without quotes** and without `$`\n- returns a **new table** and leaves the old one unchanged\n:::\n\nWe build **one pipeline**, one verb at a time.\nThe highlighted line is the new one.\n:::\n\n::::\n\n## `filter()`: keep rows {#sec-filter .smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\" code-line-numbers=\"2\"}\ngapminder |>\n  filter(continent == \"Europe\", year == 2007)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 6\n  country                continent  year lifeExp      pop gdpPercap\n  <fct>                  <fct>     <int>   <dbl>    <int>     <dbl>\n1 Albania                Europe     2007    76.4  3600523     5937.\n2 Austria                Europe     2007    79.8  8199783    36126.\n3 Belgium                Europe     2007    79.4 10392226    33693.\n4 Bosnia and Herzegovina Europe     2007    74.9  4552198     7446.\n5 Bulgaria               Europe     2007    73.0  7322858    10681.\n# ℹ 25 more rows\n```\n\n\n:::\n:::\n\n\n. . .\n\n- A condition is built from the **logical operators** of week 3: `==`, `!=`, `<`, `>`, `%in%` and friends ([the table in week 3](week03.html#/sec-logical)).\n- A comma between conditions means **and**, `|` means **or**.\n\n## `select()`: keep columns {#sec-select .smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\" code-line-numbers=\"3\"}\ngapminder |>\n  filter(continent == \"Europe\", year == 2007) |>\n  select(country, lifeExp, pop, gdpPercap)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 4\n  country                lifeExp      pop gdpPercap\n  <fct>                    <dbl>    <int>     <dbl>\n1 Albania                   76.4  3600523     5937.\n2 Austria                   79.8  8199783    36126.\n3 Belgium                   79.4 10392226    33693.\n4 Bosnia and Herzegovina    74.9  4552198     7446.\n5 Bulgaria                  73.0  7322858    10681.\n# ℹ 25 more rows\n```\n\n\n:::\n:::\n\n\n. . .\n\nA minus drops a column instead: `select(-continent)`.\n\n## Practice: filter and select {#sec-practice-filter-select .smaller}\n\n**Do this now.**\n\n1. Keep the Asian countries in 1952, with only `country` and `lifeExp`.\n2. Which countries had a life expectancy above 80 in 2007?\n3. **Stretch:** keep only the nine countries of our file, in every year.\n   Hint: `%in%` and the `country` column of `lifeexp_wide`.\n\n. . .\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ngapminder |>\n  filter(continent == \"Asia\", year == 1952) |>\n  select(country, lifeExp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 33 × 2\n  country     lifeExp\n  <fct>         <dbl>\n1 Afghanistan    28.8\n2 Bahrain        50.9\n3 Bangladesh     37.5\n4 Cambodia       39.4\n5 China          44  \n# ℹ 28 more rows\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ngapminder |>\n  filter(lifeExp > 80, year == 2007) |>\n  select(country, lifeExp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 13 × 2\n  country          lifeExp\n  <fct>              <dbl>\n1 Australia           81.2\n2 Canada              80.7\n3 France              80.7\n4 Hong Kong, China    82.2\n5 Iceland             81.8\n# ℹ 8 more rows\n```\n\n\n:::\n:::\n\n:::\n\n::::\n\n## Practice: filter and select, the stretch {#sec-practice-filter-select-stretch .smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ngapminder |>\n  filter(country %in% lifeexp_wide$country)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 108 × 6\n  country continent  year lifeExp      pop gdpPercap\n  <fct>   <fct>     <int>   <dbl>    <int>     <dbl>\n1 France  Europe     1952    67.4 42459667     7030.\n2 France  Europe     1957    68.9 44310863     8663.\n3 France  Europe     1962    70.5 47124000    10560.\n4 France  Europe     1967    71.6 49569000    13000.\n5 France  Europe     1972    72.4 51732000    16107.\n# ℹ 103 more rows\n```\n\n\n:::\n:::\n\n\n. . .\n\nNine countries times twelve years: 108 rows, the same as our tidy `lifeexp`, with the three extra columns of gapminder.\n\n## `mutate()`: new or changed columns {#sec-mutate .smaller}\n\n::: notes\n`1e6` is a million, `1e9` a billion.\nSeveral columns in one `mutate()`, separated by commas.\nPoint at the column type under `country`: `<fct>` became `<chr>`.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\" code-line-numbers=\"4-8\"}\ngapminder |>\n  filter(continent == \"Europe\", year == 2007) |>\n  select(country, lifeExp, pop, gdpPercap) |>\n  mutate(\n    country = as.character(country),\n    pop_m = pop / 1e6,\n    gdp_bn = pop * gdpPercap / 1e9\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 6\n  country                lifeExp      pop gdpPercap pop_m gdp_bn\n  <chr>                    <dbl>    <int>     <dbl> <dbl>  <dbl>\n1 Albania                   76.4  3600523     5937.  3.60   21.4\n2 Austria                   79.8  8199783    36126.  8.20  296. \n3 Belgium                   79.4 10392226    33693. 10.4   350. \n4 Bosnia and Herzegovina    74.9  4552198     7446.  4.55   33.9\n5 Bulgaria                  73.0  7322858    10681.  7.32   78.2\n# ℹ 25 more rows\n```\n\n\n:::\n:::\n\n\n. . .\n\n- A **new name** creates a new column: `pop_m`, `gdp_bn`.\n- An **existing name** changes that column: `country` was a factor (week 3), and `as.character()` makes it plain text.\n\n## `arrange()`: sort rows {#sec-arrange .smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\" code-line-numbers=\"9\"}\ngapminder |>\n  filter(continent == \"Europe\", year == 2007) |>\n  select(country, lifeExp, pop, gdpPercap) |>\n  mutate(\n    country = as.character(country),\n    pop_m = pop / 1e6,\n    gdp_bn = pop * gdpPercap / 1e9\n  ) |>\n  arrange(desc(gdp_bn))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 6\n  country        lifeExp      pop gdpPercap pop_m gdp_bn\n  <chr>            <dbl>    <int>     <dbl> <dbl>  <dbl>\n1 Germany           79.4 82400996    32170.  82.4  2651.\n2 United Kingdom    79.4 60776238    33203.  60.8  2018.\n3 France            80.7 61083916    30470.  61.1  1861.\n4 Italy             80.5 58147733    28570.  58.1  1661.\n5 Spain             80.9 40448191    28821.  40.4  1166.\n# ℹ 25 more rows\n```\n\n\n:::\n:::\n\n\n. . .\n\n`arrange()` sorts ascending, and `desc()` flips it.\n\n## Practice: mutate and arrange {#sec-practice-mutate-arrange .smaller}\n\n**Do this now.**\n\n1. For 2007, add a column `pop_m` with the population in millions.\n2. Sort so that the most populous country comes first.\n   Which five countries lead?\n3. **Stretch:** in 2007, which country had the largest economy, its total GDP in billions?\n   Is it also the richest per person?\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ngapminder |>\n  filter(year == 2007) |>\n  mutate(pop_m = pop / 1e6) |>\n  arrange(desc(pop_m)) |>\n  select(country, pop_m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 142 × 2\n  country       pop_m\n  <fct>         <dbl>\n1 China         1319.\n2 India         1110.\n3 United States  301.\n4 Indonesia      224.\n5 Brazil         190.\n# ℹ 137 more rows\n```\n\n\n:::\n:::\n\n\n## Practice: mutate and arrange, the stretch {#sec-practice-mutate-arrange-stretch .smaller}\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n**Largest economy**\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ngapminder |>\n  filter(year == 2007) |>\n  mutate(gdp_bn = pop * gdpPercap / 1e9) |>\n  arrange(desc(gdp_bn)) |>\n  select(country, gdp_bn, gdpPercap)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 142 × 3\n  country       gdp_bn gdpPercap\n  <fct>          <dbl>     <dbl>\n1 United States 12934.    42952.\n2 China          6540.     4959.\n3 Japan          4035.    31656.\n4 India          2723.     2452.\n5 Germany        2651.    32170.\n# ℹ 137 more rows\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n**Richest per person**\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ngapminder |>\n  filter(year == 2007) |>\n  mutate(gdp_bn = pop * gdpPercap / 1e9) |>\n  arrange(desc(gdpPercap)) |>\n  select(country, gdp_bn, gdpPercap)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 142 × 3\n  country       gdp_bn gdpPercap\n  <fct>          <dbl>     <dbl>\n1 Norway          228.    49357.\n2 Kuwait          119.    47307.\n3 Singapore       215.    47143.\n4 United States 12934.    42952.\n5 Ireland         167.    40676.\n# ℹ 137 more rows\n```\n\n\n:::\n:::\n\n:::\n\n::::\n\n. . .\n\nThe **United States** has the largest economy, and China the second largest, at only about 5,000 dollars per person.\n**Norway** is the richest per person, although it ranks only 40th by total GDP.\nTotal size and wealth per person are different questions.\n\n# Join {#sec-join}\n\n## Four ways to join {#sec-join-types .smaller}\n\nA **join** combines two tables by matching rows on a shared **key** column, such as `country`.\n\n::: {.small}\n| Join | Keeps |\n|---|---|\n| `left_join(x, y)` | Every row of `x`, with the matching columns of `y`, and `NA` where `y` has no match |\n| `right_join(x, y)` | Every row of `y`, with the matching columns of `x`, and `NA` where `x` has no match |\n| `inner_join(x, y)` | Only the rows that match in **both** tables |\n| `full_join(x, y)` | Every row of both tables, and `NA` wherever there is no match |\n\n: The four joins of `dplyr`. They differ only in which rows survive when a key has no partner in the other table. {#tbl-join-types}\n:::\n\n. . .\n\n::: {.callout-tip}\n**In practice, `left_join()` is nearly always the one you want.**\nYour main tibble sits on the left, and the join adds information to it from a second table.\nNo row of your main data is lost, so it is the only join we practise today.\n:::\n\n## `left_join()`: add columns from another table {#sec-left-join .smaller}\n\n::: notes\nBefore running the join, ask the prediction question on the next slide.\n:::\n\ngapminder does not know who is in the EU.\n`eu_members` does:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\neu_members <- read_csv(here(\"website\", \"slides\", \"data\", \"eu-members.csv\"))\n```\n:::\n\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\" code-line-numbers=\"3\"}\ngapminder |>\n  filter(continent == \"Europe\", year == 2007) |>\n  left_join(eu_members, by = \"country\") |>\n  select(country, lifeExp, accession_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 3\n  country                lifeExp accession_date\n  <chr>                    <dbl> <date>        \n1 Albania                   76.4 NA            \n2 Austria                   79.8 1995-01-01    \n3 Belgium                   79.4 1958-01-01    \n4 Bosnia and Herzegovina    74.9 NA            \n5 Bulgaria                  73.0 2007-01-01    \n# ℹ 25 more rows\n```\n\n\n:::\n:::\n\n\n## Practice: predict the join {#sec-practice-join .smaller}\n\n**Do this now.**\nBefore you run the join, write down:\n\n1. How many rows will the result have?\n2. What will `accession_date` hold for Norway?\n3. What happens if one table spells `\"Czechia\"` and the other `\"Czech Republic\"`?\n\n. . .\n\n1. **30**, the European countries in 2007: `left_join()` keeps every row of the left table.\n   Cyprus and Malta are in `eu_members` but not in gapminder, so they do not appear.\n2. **`NA`**: Norway has no match, and `NA` is R's missing value from week 3.\n3. Czechia silently gets `NA` too.\n\n::: {.callout-warning}\n**A join matches text exactly.**\nOne spelling difference and the row gets `NA`, without any error.\nAlways check how many `NA`s a join produced.\n:::\n\n# Summarise {#sec-summarise}\n\n## `count()`: how many rows per value {#sec-count .smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ngapminder |>\n  filter(year == 2007) |>\n  count(continent)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  continent     n\n  <fct>     <int>\n1 Africa       52\n2 Americas     25\n3 Asia         33\n4 Europe       30\n5 Oceania       2\n```\n\n\n:::\n:::\n\n\n. . .\n\n- `count()` returns one row per value of the column, with the number of rows in `n`.\n- `count(continent, sort = TRUE)` puts the largest group first.\n- Run it on any grouping variable first: how big is each group?\n\n## `summarise()`: summary statistics per group {#sec-summarise-intro .smaller}\n\n::: notes\nThis is a data summary table: step 2 of the workflow in one pipeline.\n:::\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ngapminder |>\n  filter(year == 2007) |>\n  summarise(\n    mean_life = mean(lifeExp),\n    n = n()\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  mean_life     n\n      <dbl> <int>\n1      67.0   142\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\" code-line-numbers=\"3\"}\ngapminder |>\n  filter(year == 2007) |>\n  group_by(continent) |>\n  summarise(\n    mean_life = mean(lifeExp),\n    n = n()\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  continent mean_life     n\n  <fct>         <dbl> <int>\n1 Africa         54.8    52\n2 Americas       73.6    25\n3 Asia           70.7    33\n4 Europe         77.6    30\n5 Oceania        80.7     2\n```\n\n\n:::\n:::\n\n:::\n\n::::\n\n. . .\n\nWithout groups, `summarise()` returns one row for the whole table.\n`group_by()` changes nothing you can see: it tells `summarise()` to work **once per group**.\n`n()` counts the rows of each group.\n\n## Practice: count and summarise {#sec-practice-summarise .smaller}\n\n**Do this now.**\n\n1. Count the countries per continent in 2007 with `count()`.\n2. For each continent, compute the median GDP per capita in 2007.\n3. **Stretch:** for each year, the mean life expectancy in Europe.\n   Did it ever fall?\n\n. . .\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ngapminder |>\n  filter(year == 2007) |>\n  count(continent)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  continent     n\n  <fct>     <int>\n1 Africa       52\n2 Americas     25\n3 Asia         33\n4 Europe       30\n5 Oceania       2\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ngapminder |>\n  filter(year == 2007) |>\n  group_by(continent) |>\n  summarise(median_gdp = median(gdpPercap)) |>\n  arrange(desc(median_gdp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  continent median_gdp\n  <fct>          <dbl>\n1 Oceania       29810.\n2 Europe        28054.\n3 Americas       8948.\n4 Asia           4471.\n5 Africa         1452.\n```\n\n\n:::\n:::\n\n:::\n\n::::\n\n## Practice: count and summarise, the stretch {#sec-practice-summarise-stretch .smaller}\n\n:::: {.columns}\n\n::: {.column width=\"55%\"}\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ngapminder |>\n  filter(continent == \"Europe\") |>\n  group_by(year) |>\n  summarise(mean_life = mean(lifeExp)) |>\n  print(n = 12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 2\n    year mean_life\n   <int>     <dbl>\n 1  1952      64.4\n 2  1957      66.7\n 3  1962      68.5\n 4  1967      69.7\n 5  1972      70.8\n 6  1977      71.9\n 7  1982      72.8\n 8  1987      73.6\n 9  1992      74.4\n10  1997      75.5\n11  2002      76.7\n12  2007      77.6\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"45%\"}\n**It never fell.**\nMean life expectancy in Europe rose in every five-year step, from 64.4 years in 1952 to 77.6 in 2007.\n\n`print(n = 12)` shows all twelve rows instead of the first five.\n:::\n\n::::\n\n# Your pipeline {#sec-your-pipeline}\n\n## Practice: from a question to an answer {#sec-practice-pipeline .smaller}\n\n::: notes\nEight minutes.\nWalk the room.\nPush pairs to run the pipeline after every line, not only at the end.\n:::\n\n**The question.**\nIn 2007, did European countries **inside the EU** live longer, and were they richer, than those outside?\n\n**Do this now.**\nWith `gapminder` and `eu_members` only, build one pipeline that returns one row per group, with the number of countries, the mean life expectancy and the mean GDP per capita.\n\n. . .\n\nHints:\n\n- After the join, a country is a member in 2007 if it joined in 2007 or earlier: `eu_member = !is.na(accession_date) & year(accession_date) <= 2007`.\n  `year()` comes from `lubridate`, loaded with the tidyverse.\n- Why not just `!is.na(accession_date)`?\n  Croatia is in the file, but joined in 2013.\n\n## The whole pipeline {#sec-pipeline-answer .smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\neu_2007 <- gapminder |>\n  filter(continent == \"Europe\", year == 2007) |> # rows\n  left_join(eu_members, by = \"country\") |> # add a table\n  mutate(\n    eu_member = !is.na(accession_date) & year(accession_date) <= 2007\n  ) |> # new column\n  group_by(eu_member) |> # groups\n  summarise(\n    n = n(),\n    mean_life = mean(lifeExp),\n    mean_gdppc = mean(gdpPercap)\n  ) # one row per group\neu_2007\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  eu_member     n mean_life mean_gdppc\n  <lgl>     <int>     <dbl>      <dbl>\n1 FALSE         9      76.8     19838.\n2 TRUE         21      78.0     27290.\n```\n\n\n:::\n:::\n\n\n. . .\n\n::: {.callout-important}\n**Pipelines are powerful, so test them at every step.**\nRun the pipeline after each new line and look at what it returns: how many rows, which columns, any `NA`s?\nA pipeline you have not checked step by step can be wrong without a single error message.\n:::\n\n## The answer {#sec-pipeline-conclusion .smaller}\n\n\n\n**Yes, on both counts, but by very different margins.**\n\n- The 21 EU members lived 1.2 years longer on average than the 9 countries outside: 78.0 against 76.8.\n- Their mean GDP per capita was about 7,000 US dollars higher.\n\n. . .\n\n::: {.callout-note}\n**A mean hides who is in the group.**\nThe countries outside mix Norway and Switzerland, among the richest in the data, with Albania and Bosnia and Herzegovina.\nAnd a difference between groups says nothing yet about whether membership caused it: that is step 8, the limitations.\n:::\n\n## Bonus: a table for your PDF {#sec-pipeline-kable .smaller}\n\nA printed tibble is for you.\nA reader gets a numbered, captioned table: `knitr::kable()` in a cell with a `tbl-` label and a `tbl-cap`.\n\n\n::: {#tbl-eu-2007 .cell tbl-cap='European countries in 2007, split by EU membership at the time. Members lived a little longer on average and had a clearly higher mean GDP per capita (US dollars, adjusted for inflation). Data: gapminder and the course\\'s EU membership file.'}\n\n```{.r .cell-code  code-fold=\"false\"}\neu_2007 |>\n  knitr::kable(\n    digits = 1,\n    col.names = c(\n      \"EU member\",\n      \"Countries\",\n      \"Mean life expectancy\",\n      \"Mean GDP per capita\"\n    )\n  )\n```\n\n::: {.cell-output-display}\n\n\n|EU member | Countries| Mean life expectancy| Mean GDP per capita|\n|:---------|---------:|--------------------:|-------------------:|\n|FALSE     |         9|                 76.8|             19838.4|\n|TRUE      |        21|                 78.0|             27289.9|\n\n\n:::\n:::\n\n\nIn the text, `@tbl-eu-2007` becomes a clickable \"Table 1\".\n\n# Wrap-up {#sec-wrap-up}\n\n## Summary {#sec-summary .smaller}\n\nToday we:\n\n- recapped the **cell options** and how to tell **R, Quarto and LaTeX** errors apart\n- **installed** and **loaded** packages, and called functions as `package::function()`\n- met the **tidyverse** and the three rules of **tidy data**\n- **read** a file, made it **tidy** with `pivot_longer()`\n- **transformed** it with `filter()`, `select()`, `mutate()` and `arrange()`\n- **joined** a second table with `left_join()`, then **counted** and **summarised** by group\n- answered a question with **one pipeline**, and turned the result into a captioned table\n\n## Homework {#sec-homework .smaller}\n\n- `hw-04`: wrangle the ParlGov election data with today's verbs, due 7 October.\n  Linked from the Schedule.\n- A sample solution is published after the due date.\n\n::: {.callout-important}\n**Individual feedback is only available through the opt-in path.**\nAdd an open-source `license.md` to your submission repo to opt in.\n:::\n\n::: {.callout-tip}\n**Do the DataCamp course \"Introduction to the Tidyverse\" this week.**\nIt drills today's verbs until they are automatic, with gapminder as its dataset.\nHow to join the course group is on the [syllabus](https://qmir-2026-fall.github.io/syllabus.html#sec-practice-materials).\n:::\n\n## Next week {#sec-next-week}\n\n**Data visualisation**\n\n- From a table to a figure with `ggplot2`.\n- Every plot starts from a tidy table, which is why today came first.\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}